host_key_file = "./host_key"

[buckets.test]
# endpoint = "http://endpoint"
# s3_force_path_style = false
# disable_ssl = false
bucket_url = "s3://BUCKET/PREFIX"
# bucket = BUCKET
# key_prefix = PREFIX
profile = "xxx"
region = "ap-northeast-1"
auth = "test"

# [buckets.test.credentials]
# aws_access_key_id = "aaa"
# aws_secret_access_key = "bbb"

[auth.test]
type = "inplace"

[auth.test.users.user01]
password = "test"
public_keys = """
...
"""

[auth.test.users.user02]
password = "$2a$04$IdGko3VpUeqY/HEFv5olLOa/E.dswOKxSEivXDSYnvXLWRQyJSFOi" # test
authentication_method = "bcrypt"
public_keys = """
...
"""

[auth.test.users.user03]
password = "test"
chroot = "users/user03"
